package com.littlebean.dao;

import com.littlebean.model.LeaveInfo;
import com.littlebean.model.TongJi;
import com.littlebean.model.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("leaveDao")
public interface LeaveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int insert(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int insertSelective(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    LeaveInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int updateByPrimaryKeySelective(LeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_info
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int updateByPrimaryKey(LeaveInfo record);

    List<LeaveInfo> queryLeaveAll(LeaveInfo leaveInfo);

    LeaveInfo getLeaveInfoTaskId(@Param("proId") String proId);

    List<TongJi> queryTongjiCounts();

    User getUserByProId(@Param("proId") String proId);

}