package com.littlebean.dao;

import com.littlebean.model.User;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

@Component("userDao")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri May 20 16:29:05 CST 2022
     */
    int updateByPrimaryKey(User record);
    /**
     * 分页查询所有用户
     */
    List<User> queryUserAll(User user);

    /**
     * 登录验证
     */
    User queryUserByUserNameAndPwdAndType(@RequestParam("username") String username,
                                          @RequestParam("password") String password,
                                          @RequestParam("roleName") String roleName);

    User queryUserInfoByTypeAndRoleAndDeptId(@RequestParam("type") String type,
                                            @RequestParam("role") String role,
                                            @RequestParam("deptId") String deptId);

    int updatePassword(User user);

}
